name: Build Android Release APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_TOOL_OPTIONS: "-Djava.awt.headless=true"
      GRADLE_OPTS: "-Djava.awt.headless=true -Dorg.gradle.daemon=false"
      STORE_PASSWORD: "mypassword123"
      KEY_PASSWORD: "mypassword123"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle 9.3.1
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.3.1'

      - name: Create Release Keystore and Build Release APK
        run: |
          # 1. Genera la chiave di rilascio my-upload-key.jks con alias "upload"
          keytool -genkey -v -keystore my-upload-key.jks -storepass mypassword123 -alias upload -keypass mypassword123 -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Release,O=SideGallery,C=US"

          # 2. Compila la versione Release ottimizzata
          gradle assembleRelease --no-daemon -Pandroidx.compose.compiler.suppressKotlinVersionCompatibilityCheck=true

      - name: Upload Release APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: "**/build/outputs/apk/release/*.apk"
